on:
  workflow_call:
    inputs:
    secrets:

jobs:
  branch-naming:
    runs-on: ubuntu-20.04
    steps:
      - name: Check branch naming
        uses: deepakputhraya/action-branch-name@master
        with:
          regex: '([a-z])+\/([a-z][a-z-0-9]*[a-z0-9])'
          allowed_prefixes: 'feat,fix,devops,bump'
          ignore: develop
          min_length: 5
          max_length: 30

